env:
    GITHUB_TOKEN: ENCRYPTED[63126c9152d2fede43ec7f7a5e4ed3fc1f407cd838c60411dc92933a9cffd8fa6a79af3cc44e898cc0cdc09ccf483ffd]
    
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 40G

  clone_script:
      - curl -sL https://raw.githubusercontent.com/Nico170420/CI-Scripts/shrp/clone.sh | bash

  building_script:
      - curl -sL https://raw.githubusercontent.com/Nico170420/CI-Scripts/shrp/building.sh | bash

  Upload_script:
      - curl -sL https://raw.githubusercontent.com/Nico170420/CI-Scripts/shrp/upload.sh | bash

  Upload2_script:
      - curl -sL https://raw.githubusercontent.com/Nico170420/CI-Scripts/shrp/upload2.sh | bash

