env:
    GITHUB_TOKEN: ENCRYPTED[63126c9152d2fede43ec7f7a5e4ed3fc1f407cd838c60411dc92933a9cffd8fa6a79af3cc44e898cc0cdc09ccf483ffd]
    
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "SHRP Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G

  Repo Sync_script:
      - curl -sL https://raw.githubusercontent.com/U89-sk/RecoveryBuilderCIScripts/main/shrp/reposync.sh | bash
      
  Device Tree Cloning_script:
      - curl -sL https://raw.githubusercontent.com/U89-sk/RecoveryBuilderCIScripts/main/dtclone.sh | bash

  Building_script:
      - curl -sL https://raw.githubusercontent.com/U89-sk/RecoveryBuilderCIScripts/main/building.sh | bash

  Uploading_script:
      - curl -sL https://raw.githubusercontent.com/U89-sk/RecoveryBuilderCIScripts/main/uploading.sh | bash

  #Upload2_script:
      #- curl -sL https://raw.githubusercontent.com/Nico170420/CI-Scripts/shrp/upload2.sh | bash

